(function(){
  const css='.test-status-view{max-width:none!important;width:100%!important}.test-status-view .qa-hero,.test-status-view .qa-card{background:#fff;border:1px solid #e1e8f3;border-radius:16px;box-shadow:0 8px 22px rgba(25,48,85,.05);padding:22px;margin-bottom:16px}.test-status-view .qa-eyebrow{color:#2563eb;font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.test-status-view h2{margin:7px 0;color:#17233d;font-size:28px}.test-status-view h3{margin:0 0 12px;color:#17233d}.test-status-view .qa-muted{color:#64748b;line-height:1.6}.test-status-view .qa-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:18px}.test-status-view .qa-stat{padding:16px;border-radius:12px;color:#fff;font-weight:700}.test-status-view .qa-stat b{display:block;font-size:26px;margin-top:6px}.test-status-view .qa-pass{background:linear-gradient(135deg,#16a34a,#059669)}.test-status-view .qa-skip{background:linear-gradient(135deg,#f59e0b,#d97706)}.test-status-view .qa-fail{background:linear-gradient(135deg,#ef4444,#dc2626)}.test-status-view .qa-total{background:linear-gradient(135deg,#2563eb,#4f46e5)}.test-status-view table{width:100%;border-collapse:collapse;font-size:12px}.test-status-view th,.test-status-view td{text-align:left;padding:11px;border-bottom:1px solid #edf1f7}.test-status-view th{background:#f8fafc;color:#17233d}.test-status-view .qa-ok{color:#15803d;font-weight:700}.test-status-view .qa-pending{color:#b45309;font-weight:700}@media(max-width:700px){.test-status-view .qa-stats{grid-template-columns:repeat(2,1fr)}}';
  function render(){
    const isTestStatus=location.hash==='#test-status'||location.pathname==='/test-status';
    if(!isTestStatus)return;
    document.querySelectorAll('.page').forEach(x=>x.classList.add('page-hidden'));
    let page=document.querySelector('.test-status-view');
    if(!page){page=document.createElement('section');page.className='card records-page page test-status-view';document.querySelector('main')?.appendChild(page)}
    if(!document.querySelector('#test-status-styles')){const style=document.createElement('style');style.id='test-status-styles';style.textContent=css;document.head.appendChild(style)}
    page.classList.remove('page-hidden');
    page.innerHTML='<div class="qa-hero"><div class="qa-eyebrow">Quality assurance · 26 Sep 2026</div><h2>Test case status</h2><p class="qa-muted">Evidence summary for the local Vehicle Desk application. The result page is part of the shared application shell.</p><div class="qa-stats"><div class="qa-stat qa-pass">Passed<b>3</b></div><div class="qa-stat qa-skip">Skipped<b>5</b></div><div class="qa-stat qa-fail">Failed<b>0</b></div><div class="qa-stat qa-total">Total<b>8</b></div></div></div><section class="qa-card"><h3>Automated test result</h3><p class="qa-muted">Command: <code>npm test</code></p><table><tr><th>Area</th><th>Status</th><th>Evidence</th></tr><tr><td>Server/auth contract</td><td class="qa-ok">Passed</td><td><code>/api/auth/me</code> responds correctly</td></tr><tr><td>Protected APIs</td><td class="qa-ok">Passed</td><td>Admin and external usage endpoints reject unauthenticated calls</td></tr><tr><td>RC validation</td><td class="qa-ok">Passed</td><td>Malformed registrations are rejected before provider access</td></tr><tr><td>Authenticated CRUD modules</td><td class="qa-pending">Skipped</td><td>Requires runtime admin credentials</td></tr></table></section><section class="qa-card"><h3>Load testing result</h3><p class="qa-muted">Saved vehicle <code>UP16AN0593</code>; cache-only mode; provider calls disabled.</p><table><tr><th>Concurrent requests</th><th>HTTP 200 / cache hits</th><th>Provider responses</th><th>Errors</th><th>Status</th></tr><tr><td>1,000</td><td>1,000 / 1,000</td><td>0</td><td>0</td><td class="qa-ok">Passed</td></tr><tr><td>3,000</td><td>3,000 / 3,000</td><td>0</td><td>0</td><td class="qa-ok">Passed</td></tr><tr><td>5,000</td><td>4,604 / 4,604</td><td>0</td><td>396 connection refusals</td><td class="qa-pending">Failed</td></tr></table><p class="qa-muted">Demonstrated safe capacity: <strong>3,000 concurrent cache requests</strong>. No provider calls were observed. <a href="/test/LOAD_TEST_REPORT.md">Open detailed load report</a>.</p></section><section class="qa-card"><h3>Verification notes</h3><table><tr><th>Feature</th><th>Status</th><th>Notes</th></tr><tr><td>External API usage summary</td><td class="qa-ok">Implemented</td><td>Read-only endpoint and live usage in RC responses</td></tr><tr><td>API documentation</td><td class="qa-ok">Verified</td><td>Quick start, cURL, JSON, quota, errors</td></tr><tr><td>Provider live-call path</td><td class="qa-pending">Pending</td><td>Requires provider key and external test key</td></tr></table></section>';
    document.querySelector('#pageLabel')?.replaceChildren(document.createTextNode('Test Status'));document.querySelector('#pageTitle')?.replaceChildren(document.createTextNode('Test Status'));
  }
  const deferRender=()=>window.setTimeout(render,0);
  window.addEventListener('hashchange',deferRender);window.addEventListener('pageshow',deferRender);document.addEventListener('DOMContentLoaded',deferRender);deferRender();
})();
